### ISSUE TITLE
java-spring-boot-service.yaml File Should use IAM Policy for Auto Scaling

### ISSUE THREAD

**Issue by colinbjohnson** [aws-samples/java-spring-boot-ecs-fargate-redis-caching#3]
Within the file `java-spring-boot-ecs-fargate-redis-caching/cfn/applications/java-spring-boot-service.yaml` there is a resource named `AutoScalingTarget` of type `AWS::ApplicationAutoScaling::ScalableTarget`. At issue here are two things:

1. A AWS provided IAM Managed Policy with the ARN `arn:aws:iam::aws:policy/aws-service-role/AWSApplicationAutoscalingECSServicePolicy` already exists.
2. The particular policy referenced above includes one permission (`cloudwatch:DeleteAlarm`) that the existing policy used in the document does not include.

I would suggest modifying the `AWS::IAM::Role` resource as follows:

```
AutoScalingRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Join ['', [ !Sub "${AWS::StackName}-${ServiceName}", AutoScalingRole]]
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: application-autoscaling.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/aws-service-role/AWSApplicationAutoscalingECSServicePolicy
```
